
const articles = [
  {
    image: "assets/logos/html.png",
    category: "Web Development Languages",
    title: "HTML",
    author: "Sarah smith",
  },
  {
    image: "assets/logos/css.webp",
    category: "Web Development Languages",
    title: "CSS",
    author: "David Lee",
  },
  {
    image: "assets/logos/javascript.jpg",
    category: "Web Development Languages",
    title: "JavaScript",
    author: "John Johnson",
  },
  {
    image: "assets/logos/jquery.png",
    category: "Web Development Languages",
    title: "jQuery",
    author: "John Johnson",
  },
  {
    image: "assets/logos/angular.png",
    category: "Frontend Frameworks and Libraries",
    title: "Angular",
    author: "Jessica Davis",
  },
  {
    image: "assets/logos/react.webp",
    category: "Frontend Frameworks and Libraries",
    title: "React",
    author: "Olivia Martinez",
  },
  {
    image: "assets/logos/vuejs.jpeg",
    category: "Frontend Frameworks and Libraries",
    title: "Vue",
    author: "Ava Jones",
  },
  {
    image: "assets/logos/nodejs.webp",
    category: "Backend Frameworks and Libraries",
    title: "Node.js",
    author: "Ava Jones",
  },
  {
    image: "assets/logos/expressjs.webp",
    category: "Backend Frameworks and Libraries",
    title: "Express.js",
    author: "Ava Jones",
  },
  {
    image: "assets/logos/ruby.jpeg",
    category: "Backend Frameworks and Libraries",
    title: "Ruby on Rails",
    author: "Ava Jones",
  },
  {
    image: "assets/logos/django.jpeg",
    category: "Backend Frameworks and Libraries",
    title: "Django",
    author: "Ava Jones",
  },
  {
    image: "assets/logos/flask.webp",
    category: "Backend Frameworks and Libraries",
    title: "Flask",
    author: "Ethan Thompson",
  },
  {
    image: "assets/logos/sql.png",
    category: "Database and APIs",
    title: "SQL",
    author: "Madison Davis",
  },
  {
    image: "assets/logos/nosql.png",
    category: "Database and APIs",
    title: "NoSQL",
    author: "Isabella Wilson",
  },
  {
    image: "assets/logos/restapi.jpeg",
    category: "Database and APIs",
    title: "REST APIs",
    author: "Jacob Garcia",
  },
  {
    image: "assets/logos/graphql.png",
    title: "GraphQL",
    category: "Database and APIs",
    author: "Mia Brown",
  },
  {
    image: "assets/logos/oauth.png",
    category: "Web Development Concepts and Technologies",
    title: "OAuth",
    author: "Evelyn Nguyen",
  },
  {
    image: "assets/logos/json.png",
    category: "Web Development Concepts and Technologies",
    title: "JSON",
    author: "Lian Hernandez",
  },
  {
    image: "assets/logos/ajax.gif",
    category: "Web Development Concepts and Technologies",
    title: "AJAX",
    author: "Avery Perez",
  },
  {
    image: "assets/logos/wai.jpeg",
    category: "Web Development Concepts and Technologies",
    title: "WebSockets",
    author: "Victoria Kim",
  },
  {
    image: "assets/logos/responsive.gif",
    category: "Web Development Concepts and Technologies",
    title: "Responsive Design",
    author: "Ryan Jones",
  },
  {
    image: "assets/logos/accessibility.png",
    category: "Web Development Concepts and Technologies",
    title: "Accessibilty",
    author: "Samantha Martin",
  },
  {
    image: "assets/logos/ux.jpeg",
    category: "Web Development Concepts and Technologies",
    title: "User Experience(UX)",
    author: "Luke Davis",
  },
  {
    image: "assets/logos/ui.png",
    category: "Web Development Concepts and Technologies",
    title: "User Interface (UI)",
    author: "Grace Wilson",
  },
  {
    image: "assets/logos/design-systems.jpeg",
    category: "Web Development Concepts and Technologies",
    title: "Design Systems",
    author: "Noah Martinez",
  },
  {
    image: "assets/logos/performance.png",
    category: "Web Development Concepts and Technologies",
    title: "Performance Optimization",
    author: "Chloe Taylor",
  },
  {
    image: "assets/logos/cross-browser.jpeg",
    category: "Web Development Concepts and Technologies",
    title: "Cross-Compatibility",
    author: "David Lee",
  },
  {
    image: "assets/logos/seo.jpeg",
    category: "Web Development Concepts and Technologies",
    title: "Search Engine Optimization (SEO)",
    author: "Ava Jones",
  },
  {
    image: "assets/logos/web-security.jpeg",
    category: "Web Development Concepts and Technologies",
    title: "Web Security",
    author: "Gabriel Hernandez",
  },
  {
    image: "assets/logos/testing.jpeg",
    category: "Web Development Concepts and Technologies",
    title: "Testing and Debugging",
    author: "Avery Perez",
  },
  {
    image: "assets/logos/ci-cd.jpeg",
    category: "Web Development Concepts and Technologies",
    title:
      "Continuous Integration/Continuous Integration Continuous Integration/Continuous Integration ",
    author: "Madison Davis",
  },
  {
    image: "assets/logos/devops.png",
    category: "Web Development Concepts and Technologies",
    title: "DevOps",
    author: "Isabella Wilson",
  },
  {
    image: "assets/logos/cloud.jpeg",
    category: "Web Development Concepts and Technologies",
    title: "Cloud Computing",
    author: "Jacob Garcia",
  },
  {
    image: "assets/logos/docker.png",
    category: "Web Development Concepts and Technologies",
    title: "Docker",
    author: "Mia Brown",
  },
  {
    image: "assets/logos/microservices.png",
    category: "Web Development Concepts and Technologies",
    title: "MicroServices",
    author: "Evelyn Nguyen",
  },
  {
    image: "assets/logos/pwa.png",
    category: "Web Development Concepts and Technologies",
    title: "Progressive Web Apps",
    author: "Lian Hernandez",
  },
  {
    image: "assets/logos/wai.jpeg",
    category: "Web Development Concepts and Technologies",
    title: "Web Accessibility Initiaive (WAI)",
    author: "Avery Perez",
  },
  {
    image: "assets/logos/cms.png",
    category: "Web Development Concepts and Technologies",
    title: "Content Mangment Systems (CMS)",
    author: "Victoria Kim",
  },
  {
    image: "assets/logos/analytics.png",
    category: "Web Development Concepts and Technologies",
    title: "Web Analytics",
    author: "Ryan Jones",
  },
];
